version: "3.9"
services:
  webapp:
    container_name: webapp
    image: test_flask
    restart: always
    depends_on:
      - database
      - crawler
    ports:
      - 8282:8000

  database:
    container_name: database
    image: jeunna/travel_mysql
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    command:
      mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3308:3306"

  crawler:
    container_name: crawler
    image: jeunna/travel_crawler
    restart: always
    volumes:
      - ./crawler:/crawler
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - database
    ports:
      - "8080:8080"
    