version: "3.9"
services:
  webapp:
    container_name: webapp
    build: .
    restart: always
    command:
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webqpp:/service
    ports:
      - 8282:8000
    depends_on:
      - database
      - crawler

  database:
    container_name: database
    image: mysql:5.7
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    command:
      mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3308:3306"

  crawler:
    container_name: crawler
    image: travel_crawler
    restart: always
    volumes:
      - ./crawler:/crawler
    stdin_open: true
    tty: true
    depends_on:
      - database
    ports:
      - "8080:8080"
    